"""add_employee_extended_fields

Revision ID: 24966fed0eec
Revises: 749d41c5f021
Create Date: 2026-02-23 02:08:51.809889
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '24966fed0eec'
down_revision: Union[str, None] = '749d41c5f021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('workers', sa.Column('last_name', sa.String(length=128), nullable=True))
    op.add_column('workers', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('workers', sa.Column('place_of_birth', sa.String(length=255), nullable=True))
    op.add_column('workers', sa.Column('country_of_birth', sa.String(length=100), nullable=True))
    op.add_column('workers', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('workers', sa.Column('ethnicity', sa.String(length=100), nullable=True))
    op.add_column('workers', sa.Column('religion', sa.String(length=100), nullable=True))
    op.add_column('workers', sa.Column('next_of_kin_name', sa.String(length=255), nullable=True))
    op.add_column('workers', sa.Column('next_of_kin_phone', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('passport_number', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('passport_place_of_issue', sa.String(length=255), nullable=True))
    op.add_column('workers', sa.Column('passport_issue_date', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('employee_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'employee_type')
    op.drop_column('workers', 'employee_id')
    op.drop_column('workers', 'passport_issue_date')
    op.drop_column('workers', 'passport_place_of_issue')
    op.drop_column('workers', 'passport_number')
    op.drop_column('workers', 'next_of_kin_phone')
    op.drop_column('workers', 'next_of_kin_name')
    op.drop_column('workers', 'religion')
    op.drop_column('workers', 'ethnicity')
    op.drop_column('workers', 'gender')
    op.drop_column('workers', 'country_of_birth')
    op.drop_column('workers', 'place_of_birth')
    op.drop_column('workers', 'postal_code')
    op.drop_column('workers', 'last_name')
    op.drop_column('workers', 'first_name')
    # ### end Alembic commands ###
