"""add_document_checklist_and_file_storage

Revision ID: 45cd851e1dd0
Revises: 843bd76429ec
Create Date: 2026-02-23 02:37:26.770913
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '45cd851e1dd0'
down_revision: Union[str, None] = '843bd76429ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_checklist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'UPLOADED', 'VERIFIED', 'REJECTED', 'NOT_APPLICABLE', name='checkliststatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('documents', sa.Column('file_mime', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('checklist_item_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_checklist', ['checklist_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'checklist_item_id')
    op.drop_column('documents', 'file_mime')
    op.drop_column('documents', 'file_data')
    op.drop_table('document_checklist')
    # ### end Alembic commands ###
