"""initial_schema

Revision ID: 749d41c5f021
Revises: 
Create Date: 2026-02-20 14:22:54.379272
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '749d41c5f021'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('licence_number', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Enum('A', 'B', name='licencerating'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('cos_allocated', sa.Integer(), nullable=False),
    sa.Column('cos_used', sa.Integer(), nullable=False),
    sa.Column('authorised_officer', sa.String(length=255), nullable=True),
    sa.Column('key_contact', sa.String(length=255), nullable=True),
    sa.Column('licence_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_sms_update', sa.DateTime(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.Enum('COMPLIANT', 'MINOR_BREACH', 'SUSPENSION_RISK', 'REVOCATION_RISK', 'CIVIL_PENALTY', 'ILLEGAL_WORKER', name='riskcategory'), nullable=False),
    sa.Column('portal_enabled', sa.Boolean(), nullable=False),
    sa.Column('portal_show_cos_ref', sa.Boolean(), nullable=False),
    sa.Column('portal_show_salary', sa.Boolean(), nullable=False),
    sa.Column('portal_require_edit_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licence_number')
    )
    op.create_table('key_personnel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sms_role', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('removed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_change_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_to_ho', sa.Boolean(), nullable=False),
    sa.Column('report_deadline', sa.DateTime(), nullable=True),
    sa.Column('reported_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('assessed_date', sa.DateTime(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('COMPLIANT', 'MINOR_BREACH', 'SUSPENSION_RISK', 'REVOCATION_RISK', 'CIVIL_PENALTY', 'ILLEGAL_WORKER', name='riskcategory'), nullable=False),
    sa.Column('annex_c1_triggers', sa.JSON(), nullable=True),
    sa.Column('annex_c2_triggers', sa.JSON(), nullable=True),
    sa.Column('annex_c3_triggers', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('ni_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('soc_code', sa.String(length=10), nullable=True),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('route', sa.String(length=100), nullable=False),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('is_hybrid', sa.Boolean(), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('termination_date', sa.DateTime(), nullable=True),
    sa.Column('visa_expiry', sa.DateTime(), nullable=True),
    sa.Column('passport_expiry', sa.DateTime(), nullable=True),
    sa.Column('brp_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_rtw_check', sa.DateTime(), nullable=True),
    sa.Column('next_rtw_check', sa.DateTime(), nullable=True),
    sa.Column('entry_clearance_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'TERMINATED', name='workerstatus'), nullable=False),
    sa.Column('stage', sa.Enum('RECRUITMENT', 'COS_ASSIGNMENT', 'PRE_START', 'ACTIVE_SPONSORSHIP', 'TERMINATED', name='workerstage'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('dbs_required', sa.Boolean(), nullable=False),
    sa.Column('dbs_completed', sa.Boolean(), nullable=False),
    sa.Column('atas_required', sa.Boolean(), nullable=False),
    sa.Column('atas_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.Enum('VISA_EXPIRY', 'PASSPORT_EXPIRY', 'BRP_EXPIRY', 'MISSING_DOCUMENT', 'SALARY_RISK', 'ABSENCE', 'REPORTING_DEADLINE', 'REGISTRATION_EXPIRY', 'COS_ANOMALY', 'WORKER_NOT_STARTED', 'VISA_REFUSED', 'LOCATION_CHANGE', 'FEE_RECOVERY_BREACH', 'LICENCE_RISK', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('absence_type', sa.Enum('AUTHORISED', 'UNAUTHORISED', 'SICK', 'ANNUAL_LEAVE', 'UNPAID', 'OTHER', name='absencetype'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('authorised', sa.Boolean(), nullable=False),
    sa.Column('authorised_by', sa.String(length=255), nullable=True),
    sa.Column('exceeds_10_days', sa.Boolean(), nullable=False),
    sa.Column('unpaid_exceeds_4_weeks', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_detail_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='contactchangestatus'), nullable=False),
    sa.Column('worker_confirmed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cos_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('cos_number', sa.String(length=50), nullable=False),
    sa.Column('cos_type', sa.Enum('DEFINED', 'UNDEFINED', name='costype'), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.String(length=255), nullable=True),
    sa.Column('atas_required', sa.Boolean(), nullable=False),
    sa.Column('atas_certificate_ref', sa.String(length=100), nullable=True),
    sa.Column('isc_paid', sa.Boolean(), nullable=False),
    sa.Column('isc_amount', sa.Float(), nullable=True),
    sa.Column('fee_recovery_compliant', sa.Boolean(), nullable=False),
    sa.Column('close_relative_flag', sa.Boolean(), nullable=False),
    sa.Column('route_mismatch_flag', sa.Boolean(), nullable=False),
    sa.Column('salary_inconsistency_flag', sa.Boolean(), nullable=False),
    sa.Column('duration_anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cos_number')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRING_SOON', 'EXPIRED', 'MISSING', 'NEEDS_RESUBMISSION', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_role', sa.String(length=50), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_packs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('pack_type', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('body_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruitments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('job_advert_uploaded', sa.Boolean(), nullable=False),
    sa.Column('job_advert_url', sa.Text(), nullable=True),
    sa.Column('rlmt_applicable', sa.Boolean(), nullable=False),
    sa.Column('rlmt_completed', sa.Boolean(), nullable=False),
    sa.Column('rlmt_notes', sa.Text(), nullable=True),
    sa.Column('genuine_vacancy_confirmed', sa.Boolean(), nullable=False),
    sa.Column('genuine_vacancy_checklist', sa.JSON(), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('skill_level_validated', sa.Boolean(), nullable=False),
    sa.Column('salary_threshold_validated', sa.Boolean(), nullable=False),
    sa.Column('soc_code_validated', sa.Boolean(), nullable=False),
    sa.Column('vacancy_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=255), nullable=False),
    sa.Column('deadline_type', sa.Enum('TEN_WORKING_DAYS', 'TWENTY_WORKING_DAYS', name='reportdeadlinetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DUE_SOON', 'OVERDUE', 'SUBMITTED', name='reportstatus'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('evidence_document_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('previous_salary', sa.Float(), nullable=True),
    sa.Column('new_salary', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('below_threshold_flag', sa.Boolean(), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPLIANCE_MANAGER', 'HR_OFFICER', 'PAYROLL_OFFICER', 'INSPECTOR', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('work_location_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('previous_location', sa.String(length=255), nullable=True),
    sa.Column('new_location', sa.String(length=255), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('reported_to_ho', sa.Boolean(), nullable=False),
    sa.Column('report_deadline', sa.DateTime(), nullable=True),
    sa.Column('reported_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='workerrequeststatus'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_days', sa.Integer(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_requests')
    op.drop_table('work_location_changes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('salary_history')
    op.drop_table('reports')
    op.drop_table('recruitments')
    op.drop_table('professional_registrations')
    op.drop_table('notifications')
    op.drop_table('inspection_packs')
    op.drop_table('documents')
    op.drop_table('cos_assignments')
    op.drop_table('contact_detail_changes')
    op.drop_table('attendance_records')
    op.drop_table('alerts')
    op.drop_table('workers')
    op.drop_table('risk_assessments')
    op.drop_table('org_change_logs')
    op.drop_table('key_personnel')
    op.drop_table('organisations')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
