"""add_sponsorship_fields

Revision ID: 843bd76429ec
Revises: 24966fed0eec
Create Date: 2026-02-23 02:24:24.641855
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '843bd76429ec'
down_revision: Union[str, None] = '24966fed0eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('work_address', sa.Text(), nullable=True))
    op.add_column('workers', sa.Column('sponsorship_number', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('visa_grant_date', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('job_application_date', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('offer_letter_date', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('cos_assigned_date', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('sort_code', sa.String(length=20), nullable=True))
    op.add_column('workers', sa.Column('brp_reference', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('brp_issue_date', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('dbs_check_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'dbs_check_date')
    op.drop_column('workers', 'brp_issue_date')
    op.drop_column('workers', 'brp_reference')
    op.drop_column('workers', 'sort_code')
    op.drop_column('workers', 'bank_account_number')
    op.drop_column('workers', 'cos_assigned_date')
    op.drop_column('workers', 'offer_letter_date')
    op.drop_column('workers', 'job_application_date')
    op.drop_column('workers', 'visa_grant_date')
    op.drop_column('workers', 'sponsorship_number')
    op.drop_column('workers', 'work_address')
    # ### end Alembic commands ###
