"""add_bg_verification_tables

Revision ID: d5d2333fb753
Revises: 124bc1a90788
Create Date: 2026-02-23 20:20:44.431378
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd5d2333fb753'
down_revision: Union[str, None] = '124bc1a90788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bg_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REFERENCES', 'EMAILS_SENT', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='bgverificationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('initiated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bg_verification_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('verification_id', sa.String(length=36), nullable=False),
    sa.Column('referee_name', sa.String(length=255), nullable=False),
    sa.Column('referee_email', sa.String(length=255), nullable=False),
    sa.Column('referee_phone', sa.String(length=50), nullable=True),
    sa.Column('referee_company', sa.String(length=255), nullable=False),
    sa.Column('referee_job_title', sa.String(length=255), nullable=True),
    sa.Column('relation_to_employee', sa.String(length=100), nullable=True),
    sa.Column('employment_start', sa.Date(), nullable=True),
    sa.Column('employment_end', sa.Date(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'EMAIL_SENT', 'COMPLETED', 'DECLINED', name='referencestatus'), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('response_rating', sa.Integer(), nullable=True),
    sa.Column('response_comments', sa.Text(), nullable=True),
    sa.Column('response_confirm_employment', sa.Boolean(), nullable=True),
    sa.Column('response_confirm_dates', sa.Boolean(), nullable=True),
    sa.Column('response_confirm_title', sa.Boolean(), nullable=True),
    sa.Column('response_recommend', sa.Boolean(), nullable=True),
    sa.Column('response_reason_for_leaving', sa.Text(), nullable=True),
    sa.Column('response_additional_comments', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['bg_verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bg_verification_references_token'), 'bg_verification_references', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bg_verification_references_token'), table_name='bg_verification_references')
    op.drop_table('bg_verification_references')
    op.drop_table('bg_verifications')
    # ### end Alembic commands ###
